# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/My Drive/Development/Python/ConvertUiToPy/src/gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        main_window = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 283)
        font = QtGui.QFont()
        font.setFamily("Verdana,sans-serif")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("G:/My Drive/Development/Python/ConvertUiToPy/src/gui\\logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* Algemene instellingen voor het dark thema */\n"
"QWidget {\n"
"    background-color: #000000; /* Zwarte achtergrond */\n"
"    color: #FFFFFF; /* Witte tekst */\n"
"    font-family: Verdana, sans-serif; /* Verdana font */\n"
"}\n"
"\n"
"/* Specifieke instellingen voor labels */\n"
"QLabel {\n"
"    color: #FFFFFF; /* Witte tekst voor labels */\n"
"}\n"
"\n"
"/* Instellingen voor knoppen */\n"
"QPushButton {\n"
"    background-color: #FFA500; /* Oranje achtergrond voor knoppen */\n"
"    color: #000000; /* Zwarte tekst op knoppen */\n"
"    border-radius: 8px; /* Afgeronde hoeken */\n"
"    padding: 5px 10px; /* Optioneel: wat padding toevoegen voor een betere uitstraling */\n"
"    font-family: Verdana, sans-serif; /* Verdana font voor knoppen */\n"
"}\n"
"\n"
"/* Optioneel: Hover effect voor knoppen */\n"
"QPushButton:hover {\n"
"    background-color: #FF8C00; /* Iets donkerdere oranje achtergrond bij hover */\n"
"}\n"
"\n"
"/* Instellingen voor verzonken, 3D-effect op tekstvelden */\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: #FFFFFF; /* Witte achtergrond voor tekstvelden */\n"
"    color: #000000; /* Zwarte tekst */\n"
"    border: 2px inset #888888; /* Grijze verzonken rand voor een 3D-effect */\n"
"    padding: 2px; /* Wat ruimte tussen de tekst en de rand */\n"
"    font-family: Verdana, sans-serif; /* Verdana font */\n"
"}\n"
"\n"
"/* Instellingen voor verzonken, 3D-effect op QListView */\n"
"QListView {\n"
"    background-color: #FFFFFF; /* Witte achtergrond voor QListView */\n"
"    color: #000000; /* Zwarte tekst */\n"
"    border: 2px inset #888888; /* Grijze verzonken rand voor een 3D-effect */\n"
"    padding: 2px; /* Wat ruimte tussen de items en de rand */\n"
"    font-family: Verdana, sans-serif; /* Verdana font */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LblSource = QtWidgets.QLabel(self.centralwidget)
        self.LblSource.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.LblSource.setObjectName("LblSource")
        self.txtDownloadLink = QtWidgets.QTextEdit(self.centralwidget)
        self.txtDownloadLink.setGeometry(QtCore.QRect(10, 30, 441, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDownloadLink.sizePolicy().hasHeightForWidth())
        self.txtDownloadLink.setSizePolicy(sizePolicy)
        self.txtDownloadLink.setMinimumSize(QtCore.QSize(0, 0))
        self.txtDownloadLink.setSizeIncrement(QtCore.QSize(-1, 0))
        self.txtDownloadLink.setBaseSize(QtCore.QSize(1, 1))
        self.txtDownloadLink.setObjectName("txtDownloadLink")
        self.btnSelectSourceFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectSourceFile.setGeometry(QtCore.QRect(10, 70, 441, 31))
        self.btnSelectSourceFile.setObjectName("btnSelectSourceFile")
        self.btnSelectDestination = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectDestination.setGeometry(QtCore.QRect(10, 170, 441, 31))
        self.btnSelectDestination.setObjectName("btnSelectDestination")
        self.txtFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.txtFilePath.setGeometry(QtCore.QRect(10, 130, 441, 31))
        self.txtFilePath.setBaseSize(QtCore.QSize(1, 1))
        self.txtFilePath.setObjectName("txtFilePath")
        self.lblDestination = QtWidgets.QLabel(self.centralwidget)
        self.lblDestination.setGeometry(QtCore.QRect(10, 110, 241, 21))
        self.lblDestination.setObjectName("lblDestination")
        self.btnExecute = QtWidgets.QPushButton(self.centralwidget)
        self.btnExecute.setGeometry(QtCore.QRect(10, 210, 441, 31))
        self.btnExecute.setObjectName("btnExecute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI converter"))
        self.LblSource.setText(_translate("MainWindow", "Source path - File to convert from .ui"))
        self.btnSelectSourceFile.setText(_translate("MainWindow", "Select source file"))
        self.btnSelectDestination.setText(_translate("MainWindow", "Select file"))
        self.lblDestination.setText(_translate("MainWindow", "Destination path - File to convert to .py"))
        self.btnExecute.setText(_translate("MainWindow", "Execute"))
